apiVersion: v1
kind: Service
metadata:
  name: adjust-server
  labels:
    app: adjust-server
spec:
  selector:
    app: adjust-server
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
