apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjust-server-deployment
  labels:
    app: adjust-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adjust-server
  template:
    metadata:
      labels:
        app: adjust-server
    spec:
      containers:
      - name: adjust-server
        image: neohuang/adjust_server:latest
        ports:
        - containerPort: 80
