apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjust-server-deployment
  labels:
    app: adjust-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: adjust-server
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: adjust-server
        team: backend
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '80'
    spec:
      containers:
      - name: adjust-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 5
          periodSeconds: 3
